version: '2'
services:
  snapudp:
    image: candysmurfhub/random-influx-udp
    container_name: snapudp
    environment:
      SNAP_VERSION: LATEST
    depends_on:
      - influx
  influx:
    container_name: influx
    image: tutum/influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "4444:4444/udp"
    expose:
      - "8083" 
      - "8086"
      - "8090"
      - "8099"
      - "4444/udp"
    environment:
      - UDP_DB=snap_udp